# Generated by Django 2.0.3 on 2018-04-24 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_datetime', models.DateTimeField()),
                ('attack_type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=255)),
                ('new_record_period', models.CharField(default='Hours', max_length=100)),
                ('access_level', models.CharField(max_length=100)),
                ('quality_data_indexing_dict_path', models.CharField(max_length=255)),
                ('data_storage_path', models.CharField(max_length=255)),
                ('csv_file', models.FileField(upload_to='uploads/')),
                ('description', models.CharField(default='No Description', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('access_level', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='attack',
            name='attack_module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Module'),
        ),
    ]
